# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wk < Formula
  desc "Git worktree helper with hooks support"
  homepage "https://github.com/lucas-stellet/wk"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lucas-stellet/wk/releases/download/v1.0.1/wk_1.0.1_darwin_amd64.tar.gz"
      sha256 "12cf1687aac63840f0871b3592d9812db7afc4eee8b8706a12dd6775ced42e02"

      def install
        bin.install "wk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lucas-stellet/wk/releases/download/v1.0.1/wk_1.0.1_darwin_arm64.tar.gz"
      sha256 "8b8d576883a16a178a40e3f85a42797f3d94648076639ff01233b57cd9777ff9"

      def install
        bin.install "wk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lucas-stellet/wk/releases/download/v1.0.1/wk_1.0.1_linux_amd64.tar.gz"
      sha256 "9e63be5e45a198085538d128d8f99f888fe8cc245ea2692258bce64baab47a3d"
      def install
        bin.install "wk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lucas-stellet/wk/releases/download/v1.0.1/wk_1.0.1_linux_arm64.tar.gz"
      sha256 "9f628c9ae0b06dbf5dc3b6e074474e8b295818054257f0c03fcbd8f79a22d177"
      def install
        bin.install "wk"
      end
    end
  end

  test do
    system "#{bin}/wk", "--help"
  end
end
