# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wk < Formula
  desc "Git worktree helper with hooks support"
  homepage "https://github.com/lucas-stellet/wk"
  version "0.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lucas-stellet/wk/releases/download/v0.6.0/wk_0.6.0_darwin_amd64.tar.gz"
      sha256 "3bfdb347d5f26da3d9370bafa87e5a955ed5e57dd5dfd8fd9775a7509ae20c09"

      def install
        bin.install "wk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lucas-stellet/wk/releases/download/v0.6.0/wk_0.6.0_darwin_arm64.tar.gz"
      sha256 "147708afd8693ed179fc0ca2430414630b44a5fa8a52e63f9d885b91aa6bf6dc"

      def install
        bin.install "wk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lucas-stellet/wk/releases/download/v0.6.0/wk_0.6.0_linux_amd64.tar.gz"
      sha256 "973e1be0d14df4ff85c1a8659e91aaa20c1192ba7d3dd4c94e75b0450b718694"
      def install
        bin.install "wk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lucas-stellet/wk/releases/download/v0.6.0/wk_0.6.0_linux_arm64.tar.gz"
      sha256 "f0d1efb3b8908c5b597952f4aab63f17d26659678dab4147be0d3ae2358303e4"
      def install
        bin.install "wk"
      end
    end
  end

  test do
    system "#{bin}/wk", "--help"
  end
end
